### ISSUE TITLE
Disallow options with invalid names

### ISSUE THREAD

**Issue by kisielk** [stvp/go-toml-config#1]
From what I can tell, an option name like

"db-connections" is invalid in toml, it has to be "db_connections". However the library does not reject such names. When parsing the error is simply that it is an invalid toml file, so it's hard to determine what is going wrong.

The library functions should probably panic if the option name is not valid.

**Comment by tysontate** [comment]
Looks like this is no longer true — keys can have dashes now: https://github.com/toml-lang/toml#keyvalue-pair
